from typing import List

from omni_parse.twitter.validation.validation import Validation
from omni_parse.twitter.typing import APIResponse
from omni_parse.twitter.response.user import Users
from omni_parse.twitter.response.tweet import Tweets
from omni_parse.twitter.response.list import TwitterLists
from omni_parse.twitter.response.error import Error

def parse_errors(response: APIResponse) -> List[Error]:
    """
    Parse for any API errors that ocurred in respone.

    Args:
        response (APIResponse): The response generated by API.
    
    Returns:
        Status: The status of the parsing.
    """
    errors = Validation.detect_errors(response=response)
    return errors


def parse_lists(response: APIResponse) -> TwitterLists:
    """
    Parse each individual list detail from response.

    Args:
        response (APIResponse): The response generated by API.

    Returns:
        TwitterList: A class containing the parsed response and status of the parsing.
    """
    validation = Validation(response=response)
    validation.validate_response_list()

    return TwitterLists(
        response=validation.response,
        status=validation.status
    )


def parse_users(response: APIResponse) -> Users:
    """
    Parse each individual user detail from response.

    Args:
        response (APIResponse): The response generated by API.
    
    Returns:
        Users: A class containing the parsed response and status of the parsing.
    """
    validation = Validation(response=response)
    validation.validate_response_user()

    return Users(
        response=validation.response,
        status=validation.status
    )


def parse_tweets(response: APIResponse, remove_promotions: bool = True) -> Tweets:
    """
    Parse each individual tweet detail from response.

    Args:
        response (APIResponse): The response generated by API.

    Returns:
        Tweets: A class containing the parsed response and status of the parsing.
    """
    validation = Validation(response=response)
    validation.validate_response_tweet()

    return Tweets(
        response=validation.response,
        remove_promotions=remove_promotions,
        status=validation.status
    )